### ISSUE TITLE
How do i get cljotdr-0.1.2-standalone.jar and cljotdr-0.1.2.jar CLASS?

### ISSUE THREAD

**Issue by xj-java** [sid5432/cljotdr#1]

**Comment by sid5432** [comment]
The latest version 0.1.3.  If you are looking for the older version, you can get it from 

     https://clojars.org/optical.fiber/cljotdr

If your question is about generating the *.jar files, you need to download the cljotdr source code, and install Leiningen from https://leiningen.org/ and then run

    lein uberjar

at the top-level directory.  Hope that helps.

**Comment by xj-java** [comment]
I do it,but...
![temp](https://user-images.githubusercontent.com/33653748/35140232-711f69a2-fd31-11e7-9cda-54eebca7692f.png)

**Comment by xj-java** [comment]
Or you can give it to me directly，cljotdr-0.1.2-standalone.jar and cljotdr-0.1.2.jar

**Comment by sid5432** [comment]
I've never tried it on Windows; not sure what is going on.  I can send the *.jar files to you (after I get back from work).  Do you have a email address or some place for me to send to you?

**Comment by xj-java** [comment]
ok,My email address  is 18173654398@163.com;
Thank you very much
